import mongoose from 'mongoose'
import dotenv from 'dotenv'
import bcrypt from 'bcryptjs'
import User from './models/User.js'
import Employee from './models/Employee.js'
import Attendance from './models/Attendance.js'
import Leave from './models/Leave.js'
import Payslip from './models/Payslip.js'

dotenv.config()

// ─── Helper: get a date N days ago ────────────────────
const daysAgo = (n) => {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(0, 0, 0, 0)
  return d
}

// ─── Helper: create a check-in time on a given date ───
const checkinTime = (baseDate, hour, minute) => {
  const d = new Date(baseDate)
  d.setHours(hour, minute, 0, 0)
  return d
}

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('MongoDB Connected ✅')

    // ── Wipe existing data ─────────────────────────────
    await Promise.all([
      User.deleteMany({}),
      Employee.deleteMany({}),
      Attendance.deleteMany({}),
      Leave.deleteMany({}),
      Payslip.deleteMany({}),
    ])
    console.log('Old data cleared ✅')

    // ─────────────────────────────────────────────────
    // 1. CREATE USERS
    // Passwords are hashed by the pre-save hook in User.js
    // ─────────────────────────────────────────────────
    const adminUser = await User.create({
      name: 'Pratyush Admin',
      email: 'admin@pratyush.com',
      password: 'admin123',
      role: 'admin',
    })

    const johnUser = await User.create({
      name: 'John Doe',
      email: 'john@pratyush.com',
      password: 'john123',
      role: 'employee',
    })

    const alexUser = await User.create({
      name: 'Alex Matthew',
      email: 'alex@pratyush.com',
      password: 'alex123',
      role: 'employee',
    })

    const davidUser = await User.create({
      name: 'David Michael',
      email: 'david@pratyush.com',
      password: 'david123',
      role: 'employee',
    })

    const sarahUser = await User.create({
      name: 'Sarah Connor',
      email: 'sarah@pratyush.com',
      password: 'sarah123',
      role: 'employee',
    })

    console.log('Users created ✅')

    // ─────────────────────────────────────────────────
    // 2. CREATE EMPLOYEE PROFILES
    // ─────────────────────────────────────────────────

    // employeeId is auto-generated by the pre-save hook
    // so we don't set it manually here

    const johnEmployee = await Employee.create({
      user: johnUser._id,
      name: 'John Doe',
      email: 'john@pratyush.com',
      position: 'Senior Software Developer',
      department: 'Engineering',
      salary: 5000,
      phone: '+91 98765 43210',
      bio: 'Full stack developer with 5 years of experience.',
      joiningDate: new Date('2022-01-15'),
    })

    const alexEmployee = await Employee.create({
      user: alexUser._id,
      name: 'Alex Matthew',
      email: 'alex@pratyush.com',
      position: 'Software Developer',
      department: 'Engineering',
      salary: 4000,
      phone: '+91 91234 56789',
      bio: 'Frontend specialist passionate about UI/UX.',
      joiningDate: new Date('2022-06-01'),
    })

    const davidEmployee = await Employee.create({
      user: davidUser._id,
      name: 'David Michael',
      email: 'david@pratyush.com',
      position: 'Associate Business Support',
      department: 'IT Support',
      salary: 3000,
      phone: '+91 99887 76655',
      bio: 'IT support specialist handling infrastructure.',
      joiningDate: new Date('2023-03-10'),
    })

    const sarahEmployee = await Employee.create({
      user: sarahUser._id,
      name: 'Sarah Connor',
      email: 'sarah@pratyush.com',
      position: 'HR Manager',
      department: 'Human Resources',
      salary: 4500,
      phone: '+91 90000 11122',
      bio: 'Managing people operations and recruitment.',
      joiningDate: new Date('2021-08-20'),
    })

    // Link employee IDs back to user documents
    await User.findByIdAndUpdate(johnUser._id, {
      employee: johnEmployee._id
    })
    await User.findByIdAndUpdate(alexUser._id, {
      employee: alexEmployee._id
    })
    await User.findByIdAndUpdate(davidUser._id, {
      employee: davidEmployee._id
    })
    await User.findByIdAndUpdate(sarahUser._id, {
      employee: sarahEmployee._id
    })

    console.log('Employee profiles created ✅')

    // ─────────────────────────────────────────────────
    // 3. CREATE ATTENDANCE RECORDS
    // Last 10 working days for each employee
    // ─────────────────────────────────────────────────

    const employees = [johnEmployee, alexEmployee,
                       davidEmployee, sarahEmployee]

    // Working day offsets (skip weekends roughly)
    const workingDayOffsets = [1, 2, 3, 4, 5, 8, 9, 10, 11, 12]

    for (const emp of employees) {
      for (const offset of workingDayOffsets) {
        const date = daysAgo(offset)

        // Vary check-in times realistically
        // Most on time (9:00-9:15), occasionally late (9:40-10:00)
        const isLateDay = offset % 5 === 0
        // Every 5th day is a late day
        const checkInHour = isLateDay ? 9 : 9
        const checkInMinute = isLateDay ? 45 : Math.floor(Math.random() * 15)
        // Late: 9:45, On time: 9:00-9:14

        const checkIn = checkinTime(date, checkInHour, checkInMinute)

        // Work 8-9 hours
        const workHours = 8 + Math.random()
        // Random between 8.0 and 9.0
        const checkOut = new Date(checkIn.getTime() +
          workHours * 60 * 60 * 1000)

        const workingHours = parseFloat(workHours.toFixed(2))
        const isLate = isLateDay

        await Attendance.create({
          employee: emp._id,
          date,
          checkIn,
          checkOut,
          workingHours,
          dayType: 'Full Day',
          status: 'Present',
          isLate,
        })
      }
    }

    console.log('Attendance records created ✅')

    // ─────────────────────────────────────────────────
    // 4. CREATE LEAVE REQUESTS
    // Mix of approved, rejected, pending
    // ─────────────────────────────────────────────────

    // John: 1 approved annual, 1 pending casual
    await Leave.create({
      employee: johnEmployee._id,
      type: 'Annual',
      startDate: new Date('2026-03-27'),
      endDate: new Date('2026-03-29'),
      reason: 'Family vacation trip',
      status: 'Approved',
      reviewedBy: adminUser._id,
      reviewedAt: new Date('2026-03-20'),
    })

    await Leave.create({
      employee: johnEmployee._id,
      type: 'Casual',
      startDate: new Date('2026-05-05'),
      endDate: new Date('2026-05-06'),
      reason: 'Personal work at home',
      status: 'Pending',
    })

    // Alex: 1 rejected casual, 1 approved sick
    await Leave.create({
      employee: alexEmployee._id,
      type: 'Casual',
      startDate: new Date('2026-03-23'),
      endDate: new Date('2026-03-24'),
      reason: 'Going for a short trip',
      status: 'Rejected',
      reviewedBy: adminUser._id,
      reviewedAt: new Date('2026-03-22'),
    })

    await Leave.create({
      employee: alexEmployee._id,
      type: 'Sick',
      startDate: new Date('2026-04-10'),
      endDate: new Date('2026-04-11'),
      reason: 'Fever and cold',
      status: 'Approved',
      reviewedBy: adminUser._id,
      reviewedAt: new Date('2026-04-09'),
    })

    // David: 1 approved sick, 1 pending annual
    await Leave.create({
      employee: davidEmployee._id,
      type: 'Sick',
      startDate: new Date('2026-03-15'),
      endDate: new Date('2026-03-16'),
      reason: 'Fracture on leg',
      status: 'Approved',
      reviewedBy: adminUser._id,
      reviewedAt: new Date('2026-03-14'),
    })

    await Leave.create({
      employee: davidEmployee._id,
      type: 'Annual',
      startDate: new Date('2026-05-10'),
      endDate: new Date('2026-05-15'),
      reason: 'Annual family gathering',
      status: 'Pending',
    })

    // Sarah: 1 approved casual
    await Leave.create({
      employee: sarahEmployee._id,
      type: 'Casual',
      startDate: new Date('2026-04-01'),
      endDate: new Date('2026-04-02'),
      reason: 'Attending a wedding',
      status: 'Approved',
      reviewedBy: adminUser._id,
      reviewedAt: new Date('2026-03-28'),
    })

    console.log('Leave records created ✅')

    // ─────────────────────────────────────────────────
    // 5. CREATE PAYSLIPS
    // Last 3 months for each employee
    // ─────────────────────────────────────────────────

    const payslipMonths = [
      { month: 2, year: 2026 },   // February 2026
      { month: 3, year: 2026 },   // March 2026
      { month: 4, year: 2026 },   // April 2026
    ]

    for (const emp of employees) {
      for (const period of payslipMonths) {
        // Vary allowances and deductions per month
        const allowances = Math.round(Math.random() * 500)
        // 0 to 500 random allowance
        const deductions = Math.round(Math.random() * 200)
        // 0 to 200 random deduction
        const netSalary = emp.salary + allowances - deductions

        await Payslip.create({
          employee: emp._id,
          period,
          basicSalary: emp.salary,
          allowances,
          deductions,
          netSalary,
          generatedBy: adminUser._id,
        })
      }
    }

    console.log('Payslips created ✅')

    // ─────────────────────────────────────────────────
    // SUMMARY
    // ─────────────────────────────────────────────────
    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log('🌱 DATABASE SEEDED SUCCESSFULLY')
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    console.log('\n📋 TEST ACCOUNTS:')
    console.log('┌─────────────┬─────────────────────────┬───────────┐')
    console.log('│ Role        │ Email                   │ Password  │')
    console.log('├─────────────┼─────────────────────────┼───────────┤')
    console.log('│ Admin       │ admin@pratyush.com      │ admin123  │')
    console.log('│ Employee    │ john@pratyush.com       │ john123   │')
    console.log('│ Employee    │ alex@pratyush.com       │ alex123   │')
    console.log('│ Employee    │ david@pratyush.com      │ david123  │')
    console.log('│ Employee    │ sarah@pratyush.com      │ sarah123  │')
    console.log('└─────────────┴─────────────────────────┴───────────┘')
    console.log('\n📊 DATA CREATED:')
    console.log('  • 1 Admin + 4 Employees')
    console.log('  • 40 Attendance records (10 days × 4 employees)')
    console.log('  • 7 Leave requests (mix of approved/rejected/pending)')
    console.log('  • 12 Payslips (3 months × 4 employees)')
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n')

    process.exit(0)
  } catch (error) {
    console.error('Seeding failed ❌', error.message)
    process.exit(1)
  }
}

seed()